[2025-03-11T00:54:02.681+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-11T00:54:02.689+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: redfin_analytics_dag.tsk_extract_redfin_data manual__2025-03-11T00:53:59.710168+00:00 [queued]>
[2025-03-11T00:54:02.694+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: redfin_analytics_dag.tsk_extract_redfin_data manual__2025-03-11T00:53:59.710168+00:00 [queued]>
[2025-03-11T00:54:02.694+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 3
[2025-03-11T00:54:02.711+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): tsk_extract_redfin_data> on 2025-03-11 00:53:59.710168+00:00
[2025-03-11T00:54:02.717+0000] {standard_task_runner.py:72} INFO - Started process 14383 to run task
[2025-03-11T00:54:02.720+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'redfin_analytics_dag', 'tsk_extract_redfin_data', 'manual__2025-03-11T00:53:59.710168+00:00', '--job-id', '49', '--raw', '--subdir', 'DAGS_FOLDER/redfin_analytics.py', '--cfg-path', '/tmp/tmp6i6s_8c3']
[2025-03-11T00:54:02.722+0000] {standard_task_runner.py:105} INFO - Job 49: Subtask tsk_extract_redfin_data
[2025-03-11T00:54:02.759+0000] {task_command.py:467} INFO - Running <TaskInstance: redfin_analytics_dag.tsk_extract_redfin_data manual__2025-03-11T00:53:59.710168+00:00 [running]> on host ip-172-31-7-71.eu-west-2.compute.internal
[2025-03-11T00:54:02.816+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='dengineer420@gmail.com' AIRFLOW_CTX_DAG_OWNER='Rahul' AIRFLOW_CTX_DAG_ID='redfin_analytics_dag' AIRFLOW_CTX_TASK_ID='tsk_extract_redfin_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-11T00:53:59.710168+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-11T00:53:59.710168+00:00'
[2025-03-11T00:54:02.817+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-11T00:54:02.818+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-11T00:54:02.819+0000] {logging_mixin.py:190} INFO - Current task name:tsk_extract_redfin_data state:running start_date:2025-03-11 00:54:02.689744+00:00
[2025-03-11T00:54:02.819+0000] {logging_mixin.py:190} INFO - Dag name:redfin_analytics_dag and current dag run status:running
[2025-03-11T00:54:02.819+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-11T00:56:37.825+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow/dags/functions.py", line 31, in extract_data
    output_list_s3.append(f"s3://{s3_bucket}/{s3_key}")
                                  ^^^^^^^^^
NameError: name 's3_bucket' is not defined
[2025-03-11T00:56:37.834+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-11T00:56:37.835+0000] {logging_mixin.py:190} INFO - Task start:2025-03-11 00:54:02.689744+00:00 end:2025-03-11 00:56:37.834456+00:00 duration:155.144712
[2025-03-11T00:56:37.835+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): tsk_extract_redfin_data> dag:<DAG: redfin_analytics_dag> dagrun:<DagRun redfin_analytics_dag @ 2025-03-11 00:53:59.710168+00:00: manual__2025-03-11T00:53:59.710168+00:00, state:running, queued_at: 2025-03-11 00:53:59.721397+00:00. externally triggered: True>
[2025-03-11T00:56:37.835+0000] {logging_mixin.py:190} INFO - Failure caused by name 's3_bucket' is not defined
[2025-03-11T00:56:37.835+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=redfin_analytics_dag, task_id=tsk_extract_redfin_data, run_id=manual__2025-03-11T00:53:59.710168+00:00, execution_date=20250311T005359, start_date=20250311T005402, end_date=20250311T005637
[2025-03-11T00:56:37.860+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-11T00:56:37.861+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 49 for task tsk_extract_redfin_data (name 's3_bucket' is not defined; 14383)
Traceback (most recent call last):
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow/dags/functions.py", line 31, in extract_data
    output_list_s3.append(f"s3://{s3_bucket}/{s3_key}")
                                  ^^^^^^^^^
NameError: name 's3_bucket' is not defined
[2025-03-11T00:56:37.912+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-11T00:56:37.923+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-11T00:56:37.924+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
